#!/usr/bin/env python3
"""Assemble + lint the A/B prod persona bodies (DSR-543).

Single source of truth: one shared ``persona-prod-base.md`` body (the High-Order
Strategic Research Agent, lifted verbatim from prod and enriched with non-routing
guidance + the neutral ToolUniverse pointer, binding rule, and Tool Balance), plus an
optional ``persona-prod-weighted-addendum.md`` (Mode 3 routing block, DSR-545). Both arms
embed the *identical* base, so they differ by exactly one factor — skill-routing weight.

Emits two paste-ready Studio bodies, each prefixed with a documentation header (an HTML
comment, which does not count toward the 10 000-char cap), then lints them. Exits nonzero
on any hard failure so the assembler doubles as the static seam.

    python assemble_prod_personas.py          # assemble + lint, report char budgets
"""

from __future__ import annotations

import sys
from pathlib import Path

import persona_lint

HERE = Path(__file__).resolve().parent
BASE = HERE / "persona-prod-base.md"
WEIGHTED_ADDENDUM = HERE / "persona-prod-weighted-addendum.md"

NEUTRAL_OUT = HERE / "persona-prod-neutral.md"
WEIGHTED_OUT = HERE / "persona-prod-weighted.md"

NEUTRAL_HEADER = """\
<!--
Agent A — NEUTRAL-TOOLS prod persona (DSR-544 / DSR-543). Assembled by
assemble_prod_personas.py from persona-prod-base.md — DO NOT edit this file by hand;
edit the base and re-run. The ToolUniverse skill/tool surface is present as ordinary
peer tools with NO routing preference: this arm tests whether mere availability gets the
skills used. Apply on swiss-rockets.squirro.com (10 000-char cap) via Studio -> Persona
(paste the body BELOW this comment). A/B partner: persona-prod-weighted.md.

Hand-test (the comparison this arm answers): does the agent SPONTANEOUSLY reach
find_skill / get_skill for a biomedical query, or default to web only?
-->
"""

WEIGHTED_HEADER = """\
<!--
Agent B — WEIGHTED-SKILLS prod persona (DSR-545 / DSR-543). Assembled by
assemble_prod_personas.py from persona-prod-base.md + persona-prod-weighted-addendum.md
— DO NOT edit this file by hand; edit the base/addendum and re-run. Same base as Agent A
plus Mode 3 (Skill-Served Biomedical Research): biomedical-entity/workflow queries route
to the skill path FIRST. Apply on swiss-rockets.squirro.com (10 000-char cap) via Studio
-> Persona (paste the body BELOW this comment). A/B partner: persona-prod-neutral.md.

Hand-test: fast-path rows route to the right get_skill(name); tail queries hit find_skill
first (no guessed names); aggregate-trial questions avoid clinical-trial-matching; web
narrative still appears alongside grounded skill output.
-->
"""


# Mode 3 is injected into this slot (right after Synthetical Mode), so the three dispatcher
# modes read 1→2→3 in order. Agent A strips the slot; Agent B fills it.
MODE3_SLOT = "<!--MODE3-->"


def _fill_slot(base: str, block: str) -> str:
    if MODE3_SLOT not in base:
        raise SystemExit(f"slot {MODE3_SLOT} missing from {BASE.name}")
    return base.replace(MODE3_SLOT, block, 1)


def assemble() -> list[tuple[Path, str]]:
    base = BASE.read_text()
    # Agent A — neutral: remove the empty slot line entirely.
    neutral = _fill_slot(base, "").replace("\n\n\n", "\n\n")
    outputs: list[tuple[Path, str]] = [(NEUTRAL_OUT, NEUTRAL_HEADER + "\n" + neutral)]
    if WEIGHTED_ADDENDUM.exists():
        # Agent B — weighted: Mode 3 takes the slot, in document order with Modes 1 and 2.
        weighted = _fill_slot(base, WEIGHTED_ADDENDUM.read_text().strip())
        outputs.append((WEIGHTED_OUT, WEIGHTED_HEADER + "\n" + weighted))
    return outputs


def main() -> int:
    failed = False
    for path, text in assemble():
        path.write_text(text)
        errors, warnings = persona_lint.check_body(text, HERE)
        n = persona_lint.body_len(text)
        status = "FAIL" if errors else "ok"
        print(f"[{status}] {path.name}: body {n}/{persona_lint.PROD_CHAR_CAP} chars")
        for w in warnings:
            print(f"    warn: {w}")
        for e in errors:
            print(f"    error: {e}")
            failed = True
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
