"""Custom tool: export_table.

Exports an AIRA session table as **HTML + CSV**.

Behaviour
---------
* If both ``SQUIRRO_CLUSTER`` and ``SQUIRRO_PROJECT`` are set, the tool
  POSTs the structured table (``cols`` + ``rows``) to the dedicated
  ``table_export`` studio plugin and returns the resulting download URLs
  — one row per format.
* If those env vars are *not* set, the tool quietly renders HTML+CSV
  locally and returns them inline (``format: "inline_local"``). This is
  the expected dev / offline path.
* If the env vars *are* set but the plugin call fails (HTTP error,
  timeout, connection refused, …), the tool **logs at ERROR level** and
  still returns inline HTML+CSV — but tagged ``format: "inline_fallback"``
  with a ``plugin_error`` field describing the failure. That way the
  caller knows to investigate the plugin instead of assuming offline mode.

PDF/DOCX are intentionally not produced — that work belongs to the
separate ``pdf_generation`` plugin.

The local renderer here is a deliberately small duplicate of the canonical
plugin renderer in ``integration/studio/table_export/rendering.py``. It
exists so the tool keeps a usable fallback when the plugin is unreachable;
when both are reachable, the plugin renderer's output is what callers see.
"""
from __future__ import annotations

import csv
import html
import io
import logging
import os
import sqlite3

log = logging.getLogger(__name__)


# --------------------------------------------------------------------------
# Pure helpers — no Squirro / Flask dependencies. Tested directly.
# --------------------------------------------------------------------------

def _read_table(db_path: str, table_name: str) -> tuple[list[str], list[list]]:
    """Return ``(cols, rows)`` for ``table_name`` in the SQLite DB.

    Raises ``ValueError`` if the table doesn't exist (so the caller can
    surface a clear error to the LLM)."""
    conn = sqlite3.connect(db_path, timeout=30)
    try:
        try:
            cur = conn.execute(f"SELECT * FROM [{table_name}] LIMIT 0")
            cols = [d[0] for d in cur.description]
            rows = [list(r) for r in conn.execute(f"SELECT * FROM [{table_name}]").fetchall()]
        except sqlite3.OperationalError as e:
            raise ValueError(f"Table '{table_name}' not found: {e}")
    finally:
        conn.close()
    return cols, rows


def _local_render_html(cols, rows, title: str) -> str:
    """Degraded local renderer for the offline / plugin-failed path.

    Aligned with ``integration/studio/table_export/rendering.render_html``
    but kept here so the tool can produce HTML without reaching the plugin.
    """
    title = title or "Export"
    e = html.escape
    parts = [
        "<!DOCTYPE html>",
        '<html><head><meta charset="UTF-8">',
        f"<title>{e(title)}</title>",
        "<style>",
        "body { font-family: Arial, sans-serif; margin: 20px; }",
        "h1 { color: #1a5276; font-size: 18px; }",
        ".meta { color: #666; font-size: 12px; margin-bottom: 16px; }",
        "table { border-collapse: collapse; width: 100%; font-size: 11px; }",
        "th { background: #1a5276; color: white; padding: 8px 10px; "
        "text-align: left; font-weight: 600; }",
        "td { padding: 6px 10px; border-bottom: 1px solid #ddd; "
        "vertical-align: top; max-width: 400px; word-wrap: break-word; }",
        "tr:nth-child(even) { background: #f8f9fa; }",
        ".footer { margin-top: 16px; font-size: 11px; color: #999; }",
        "</style></head><body>",
        f"<h1>{e(title)}</h1>",
        f'<div class="meta">{len(rows)} rows &times; {len(cols)} columns</div>',
        "<table><thead><tr>",
        "".join(f"<th>{e('' if c is None else str(c))}</th>" for c in cols),
        "</tr></thead><tbody>",
    ]
    for row in rows:
        parts.append("<tr>")
        parts.extend(f"<td>{e('' if v is None else str(v))}</td>" for v in row)
        parts.append("</tr>")
    parts.extend([
        "</tbody></table>",
        '<div class="footer">Generated by AIRA Research Pipeline (local fallback)</div>',
        "</body></html>",
    ])
    return "".join(parts)


def _local_render_csv(cols, rows) -> str:
    """RFC 4180 CSV via the stdlib ``csv`` module — handles commas, quotes."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(list(cols))
    for row in rows:
        writer.writerow(["" if v is None else v for v in row])
    return buf.getvalue()


# --------------------------------------------------------------------------
# Plugin call
# --------------------------------------------------------------------------

def _call_table_export_plugin(
    cols: list[str],
    rows: list[list],
    title: str,
    cluster: str,
    project_id: str,
    refresh_token: str,
) -> tuple[dict | None, str | None]:
    """POST to the ``table_export`` studio plugin.

    Returns ``(urls_dict, None)`` on success or ``(None, error_str)`` on
    failure. ``error_str`` is a short human-readable summary suitable for
    the ``plugin_error`` field — empty / None means "not configured", which
    callers handle as the silent inline-local path.
    """
    import requests as _rq

    url = f"{cluster.rstrip('/')}/studio/table_export/projects/{project_id}/export"
    if refresh_token:
        url = f"{url}?token={refresh_token}"

    try:
        resp = _rq.post(
            url,
            json={
                "cols": cols,
                "rows": rows,
                "title": title,
                "formats": ["html", "csv"],
            },
            headers={"Content-Type": "application/json"},
            timeout=30,
        )
        resp.raise_for_status()
        data = resp.json()
        if data.get("status") in ("success", "partial"):
            return ({
                "html_url": data.get("html_url") or "",
                "csv_url": data.get("csv_url") or "",
            }, None)
        return (None, f"plugin returned status={data.get('status')!r}: {data}")
    except _rq.exceptions.HTTPError as e:
        status = getattr(getattr(e, "response", None), "status_code", "?")
        return (None, f"POST {url} → HTTP {status} ({e})")
    except _rq.exceptions.ConnectionError as e:
        return (None, f"POST {url} → ConnectionError: {e}")
    except Exception as e:  # noqa: BLE001 — surface anything else verbatim
        return (None, f"POST {url} → {type(e).__name__}: {e}")


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------

def exec_export_table(arguments, input_table, output_table, db_path):
    """Export the chosen session table via the table_export plugin.

    The tool returns a list of dicts (the AIRA convention). One row per
    download URL on the success path; a single row with inline html/csv
    on either fallback path.
    """
    # Auto-select most-recent non-internal table when input is empty / a
    # utility-tool name. Keeps behaviour identical to the previous version.
    if not input_table or input_table in (
        "export_table", "show_table", "filter_table", "summarize_table",
    ):
        conn = sqlite3.connect(db_path, timeout=30)
        try:
            tables = [
                r[0] for r in conn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
                ).fetchall() if not r[0].startswith("_")
            ]
        finally:
            conn.close()
        if not tables:
            raise ValueError("No tables found in session. Run a tool first, then export.")
        input_table = tables[-1]
        log.info("exec_export_table: auto-selected table '%s' from %d available", input_table, len(tables))

    title = arguments.get("title") or f"AIRA Export: {input_table}"
    cols, rows = _read_table(db_path, input_table)
    log.info(
        "exec_export_table: read table '%s' (%d rows × %d cols)",
        input_table, len(rows), len(cols),
    )

    cluster = os.environ.get("SQUIRRO_CLUSTER", "")
    project_id = os.environ.get("SQUIRRO_PROJECT", "")
    refresh_token = os.environ.get("SQUIRRO_TOKEN", "")

    # No cluster/project → silent inline-local. No network call.
    if not cluster or not project_id:
        log.info("exec_export_table: SQUIRRO_CLUSTER/PROJECT not set — returning inline_local")
        return [_inline_row("inline_local", input_table, cols, rows, title, plugin_error=None)]

    urls, err = _call_table_export_plugin(cols, rows, title, cluster, project_id, refresh_token)

    if urls and any(urls.values()):
        out = []
        for fmt in ("html", "csv"):
            url = urls.get(f"{fmt}_url")
            if url:
                out.append({"format": fmt, "url": url})
        log.info("exec_export_table: uploaded — %s", {r["format"]: r["url"] for r in out})
        return out

    # Plugin call failed → loud error log + inline_fallback row.
    log.error("exec_export_table: table_export plugin call failed — %s", err)
    return [_inline_row("inline_fallback", input_table, cols, rows, title, plugin_error=err)]


def _inline_row(fmt_label, table, cols, rows, title, plugin_error):
    html_text = _local_render_html(cols, rows, title)
    csv_text = _local_render_csv(cols, rows)
    row = {
        "format": fmt_label,
        "table": table,
        "rows": len(rows),
        "html": html_text,
        "csv": csv_text,
        "message": (
            "Plugin call failed — falling back to inline content. Check the studio "
            "plugin logs and verify the `table_export` plugin is deployed."
            if fmt_label == "inline_fallback"
            else "Running without SQUIRRO_CLUSTER/PROJECT — inline content only."
        ),
    }
    if plugin_error:
        row["plugin_error"] = plugin_error
    return row
